url: https://thestandard.innovareproperties
baseurl: ''

# Site settings
title: The Standard
email: anna@innovareinvestments.com
description: "Queen Anne apartments for rent"


# Color settings (hex-codes without the leading hash-tag)
#color:
#  primary: fed136
#  secondary: fec503
#  secondary-dark: 333
# red thing A9231E
#green thing 74C1AC

color:
  primary: A9231E
  secondary: A9231E
  secondary-dark: 333
  nav-bg: F8F8FF

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 512 5th Ave W
  - line: Seattle, WA 98119

# Build settings
markdown: kramdown
permalink: pretty
